spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5435/payment
    username: ms_admin
    password: ms_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.rca.ecommerce.notification.PaymentConfirmation
server:
  port: 8070