services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: ms_admin
      POSTGRES_PASSWORD: ms_password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb_server:
    container_name: ms_mongo_db_server
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ms_mongo_server_username
      MONGO_INITDB_ROOT_PASSWORD: ms_mongo_server_password
    networks:
      - microservices-net

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ms_mongo_server_username
      ME_CONFIG_MONGODB_ADMINPASSWORD: ms_mongo_server_password
      ME_CONFIG_MONGODB_SERVER: mongodb_server
    networks:
      - microservices-net

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - microservices-net


networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: